### ISSUE TITLE
Options defined in grunt file are overridden by default options

### ISSUE THREAD

**Issue by mmitchell80** [pixel-shock/grunt-npm-check-updates#1]
Howdey,
I'm not sure why, but when I define a new template for the xml output, and set the the json output to false, I still get both the xml and the json files printed out. I don't think the default options defined in the grunt-npm-check-updates.js file is merging my settings correctly.
Thanks,
Matt

**Comment by pixel-shock** [comment]
Hi Matt,

*sorry* for my late reply ... I fixed this issue in the current 1.1.2 release 👍

**Comment by pixel-shock** [comment]
I reopened this issue until you agree with me, that the bug is fixed 😉

**Comment by mmitchell80** [comment]
@pixel-shock No problem, glad I could help, Looks good to me
