### ISSUE TITLE
The mappings between Comparator and grunt-npm-check-updates are not correct

### ISSUE THREAD

**Issue by mmitchell80** [pixel-shock/grunt-npm-check-updates#2]
Howdey,
The example output templates fail to export the installed version and the latest version. It appears these values are not mapped correctly from Comparator to the grunt file. After updating the names to match, everything appears to be working just fine.

Original
![image](https://user-images.githubusercontent.com/26092749/42185988-7ccd525e-7e10-11e8-8c2f-78d7511af2d2.png)

Fixed
![image](https://user-images.githubusercontent.com/26092749/42186000-8c1a9078-7e10-11e8-83e4-d0e657adeace.png)

Thanks,

Matt

**Comment by pixel-shock** [comment]
Hi Matt,

and again **sorry** for my late reply.
I fixed this issue in v1.1.2

**Comment by mmitchell80** [comment]
@pixel-shock No problem, glad I could help. Looks good to me
